FROM python:3.10-slim

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    tshark \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY scripts/extract_ciciot2023_http.py /app/

ENTRYPOINT ["python3", "/app/extract_ciciot2023_http.py"]
