FROM python:3.12-slim

RUN pip install --no-cache-dir flask

WORKDIR /app
COPY src/templates/safe_pseudo_shell.py /app/
COPY src/templates/cmdi_flask.py /app/

ENV SPEC_PATH=/app/spec.json

EXPOSE 8080

CMD ["python", "cmdi_flask.py"]
